AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Drug Analytics API - Serverless application for drug discovery data processing

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name for resource naming

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        API_TITLE: Drug Analytics API
        API_VERSION: 1.0.0

Resources:
  # DynamoDB Table for drug data storage
  DrugDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'DrugData-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: DrugAnalytics

  # CloudWatch Log Group for API access logs
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/apigateway/drug-analytics-${Environment}'
      RetentionInDays: 30

  # S3 Bucket for CSV file uploads
  DrugDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'drug-analytics-${Environment}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 90
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: DrugAnalytics

  # IAM Role for API Lambda Function
  ApiLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'drug-api-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::drug-analytics-${Environment}-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::drug-analytics-${Environment}-${AWS::AccountId}/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                Resource: !GetAtt DrugDataTable.Arn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: DrugAnalytics

  # IAM Role for CSV Processor Lambda Function
  CsvProcessorExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'csv-processor-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::drug-analytics-${Environment}-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::drug-analytics-${Environment}-${AWS::AccountId}/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:BatchWriteItem
                Resource: !GetAtt DrugDataTable.Arn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: DrugAnalytics

  # HTTP API Gateway
  DrugAnalyticsApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      Description: !Sub 'Drug Analytics API - ${Environment}'
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        MaxAge: 600
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50
      AccessLogSettings:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '$context.requestId $context.error.message $context.error.messageString'
      Tags:
        Environment: !Ref Environment
        Application: DrugAnalytics

  # API Lambda Function (FastAPI)
  DrugApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'drug-api-${Environment}'
      CodeUri: .
      Handler: src.main.handler
      Description: FastAPI application for drug analytics REST API
      Role: !GetAtt ApiLambdaExecutionRole.Arn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref DrugDataBucket
          DYNAMODB_TABLE_NAME: !Ref DrugDataTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref DrugAnalyticsApi
            Path: /{proxy+}
            Method: ANY
      Tags:
        Environment: !Ref Environment
        Application: DrugAnalytics

  # CSV Processor Lambda Function (NO S3 event trigger - will add manually)
  CsvProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'csv-processor-${Environment}'
      CodeUri: .
      Handler: lambda_functions.csv_processor.handler
      Description: Processes CSV files uploaded to S3 and saves to DynamoDB
      Role: !GetAtt CsvProcessorExecutionRole.Arn
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref DrugDataBucket
          DYNAMODB_TABLE_NAME: !Ref DrugDataTable
      Tags:
        Environment: !Ref Environment
        Application: DrugAnalytics

Outputs:
  S3BucketName:
    Description: S3 bucket name for CSV uploads
    Value: !Ref DrugDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3Bucket'

  DynamoDBTableName:
    Description: DynamoDB table name for drug data
    Value: !Ref DrugDataTable
    Export:
      Name: !Sub '${AWS::StackName}-DynamoDBTable'

  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${DrugAnalyticsApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/'

  ApiId:
    Description: API Gateway ID
    Value: !Ref DrugAnalyticsApi
    Export:
      Name: !Sub '${AWS::StackName}-ApiId'

  CsvProcessorFunctionArn:
    Description: CSV Processor Lambda function ARN
    Value: !GetAtt CsvProcessorFunction.Arn

  ApiLambdaRoleArn:
    Description: API Lambda execution role ARN
    Value: !GetAtt ApiLambdaExecutionRole.Arn

  CsvProcessorRoleArn:
    Description: CSV Processor Lambda execution role ARN
    Value: !GetAtt CsvProcessorExecutionRole.Arn
